import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { describe,it } from 'node:test'
import { assertA1AssignmentExecutionAuthorizationAdmission,hashA1JobSet,sumA1PlanReservations,validateA1AssignmentExecutionAuthorizationRequest,validateA1AssignmentExecutionAuthorizationState } from '../src/a1-assignment-execution-authorization.js'
import { hashA1AssignmentPlan,hashA1Mission } from '../src/a1-dispatch-authorization.js'
import type { A1AssignmentEnqueueAuthorizationState } from '../src/a1-assignment-enqueue-authorization.js'
import type { AssignmentPlan } from '../src/assignment-plan.js'
import type { MissionRecord } from '../src/repository.js'

const NOW=new Date('2026-08-29T20:00:00.000Z'),MISSION_ID='a5500000-0000-4500-8500-000000000053',TRACE_ID='a5500000-0000-4500-8500-000000000054',ENQUEUE_ID='a5500000-0000-4500-8500-000000000055',EXECUTION_ID='a5500000-0000-4500-8500-000000000056'
function mission():MissionRecord{return{mission_id:MISSION_ID,trace_id:TRACE_ID,autonomy_level:'A1',a3_enabled:false,dry_run:true,project_id:'proptimiza',offer_id:'operacion-sin-planillas'}}
function plan():AssignmentPlan{return{mission_id:MISSION_ID,trace_id:TRACE_ID,plan_version:'a1-plan-v1',assignments:[{assignment_id:'a5500000-0000-4500-8500-000000000057',idempotency_key:'a1-assignment:00000053',profile_id:'sales-orchestrator',instruction:'Clasificar únicamente evidencia interna aprobada.',evidence:'Expediente interno.',depends_on:[],usage_value_reservation_usd:0.01,maximum_tokens:6144,maximum_api_calls:3,max_attempts:1}]}}
function attestations(){return{exact_job_set_confirmed:true,authorization_record_only:true,no_jobs_claimed_by_authorization:true,no_execution:true,no_internet:true,no_contact:true,no_crm_write:true,no_external_actions:true,no_provider_credit_spend:true,global_kill_switch_required:true,execution_arm_requires_separate_gate:true}as const}
function request(){return{decision:'approved',rationale:'Registra solamente el prerrequisito exacto; no inicia ni ejecuta jobs.',reviewer_id:'director',reviewer_email:'proptimizaspa@gmail.com',reviewed_at:NOW.toISOString(),expires_at:'2026-08-29T20:15:00.000Z',expected_mission_sha256:hashA1Mission(mission()),expected_assignment_plan_sha256:hashA1AssignmentPlan(plan()),expected_job_set_sha256:hashA1JobSet(plan()),expected_enqueue_authorization_id:ENQUEUE_ID,maximum_provider_credit_spend_usd:sumA1PlanReservations(plan()),user_authorization_sha256:'f'.repeat(64),attestations:attestations(),idempotency_key:'a1-execution-auth:mission-00000053',assignment_plan:plan()}}
function parent():A1AssignmentEnqueueAuthorizationState{return{authorizationId:ENQUEUE_ID,missionId:MISSION_ID,traceId:TRACE_ID,planVersion:'a1-plan-v1',dispatchAuthorizationId:'a5500000-0000-4500-8500-000000000058',decision:'approved',rationale:'Autoriza solamente el enqueue exacto y separado.',reviewerId:'director',reviewerEmail:'proptimizaspa@gmail.com',reviewedAt:NOW.toISOString(),expiresAt:'2026-08-29T20:20:00.000Z',missionSha256:hashA1Mission(mission()),assignmentPlanSha256:hashA1AssignmentPlan(plan()),userAuthorizationSha256:'e'.repeat(64),attestations:{exactEnqueueConfirmed:true,authorizationRecordOnly:true,noAssignmentsEnqueuedByAuthorization:true,noExecution:true,noContact:true,noCrmWrite:true,noExternalActions:true,noProviderCreditSpend:true,globalKillSwitchRequired:true},idempotencyKey:'a1-enqueue-auth:mission-00000053',enqueueAuthorizationRecorded:true,assignmentEnqueuePermitted:true,assignmentsEnqueued:false,executionAuthorized:false,dispatchClaimingPermitted:false,internetAccessAllowed:false,providerCreditSpendAllowed:false,contactPermitted:false,crmWriteAllowed:false,maximumExternalActions:0,globalKillSwitchRequired:true,productionGate:'blocked',nextRequiredGate:'enqueue_exact_assignment_plan_separately',provenance:{source:'control-broker',sourceId:`a1-assignment-enqueue-authorization:${ENQUEUE_ID}`,observedAt:NOW.toISOString(),synthetic:false}}}
function state(){return{authorizationId:EXECUTION_ID,missionId:MISSION_ID,traceId:TRACE_ID,planVersion:'a1-plan-v1',enqueueAuthorizationId:ENQUEUE_ID,decision:'approved',rationale:'Registra solamente el prerrequisito exacto; no inicia ni ejecuta jobs.',reviewerId:'director',reviewerEmail:'proptimizaspa@gmail.com',reviewedAt:NOW.toISOString(),expiresAt:'2026-08-29T20:15:00.000Z',missionSha256:hashA1Mission(mission()),assignmentPlanSha256:hashA1AssignmentPlan(plan()),jobSetSha256:hashA1JobSet(plan()),assignmentIds:plan().assignments.map(item=>item.assignment_id),maximumProviderCreditSpendUsd:0.01,userAuthorizationSha256:'f'.repeat(64),attestations:{exactJobSetConfirmed:true,authorizationRecordOnly:true,noJobsClaimedByAuthorization:true,noExecution:true,noInternet:true,noContact:true,noCrmWrite:true,noExternalActions:true,noProviderCreditSpend:true,globalKillSwitchRequired:true,executionArmRequiresSeparateGate:true},idempotencyKey:'a1-execution-auth:mission-00000053',executionAuthorizationRecorded:true,dispatchExecutionEligible:true,executionArmCreated:false,dispatchClaimingPermitted:false,jobsClaimed:false,executionStarted:false,internetAccessAllowed:false,providerCreditSpendAllowed:false,contactPermitted:false,crmWriteAllowed:false,maximumExternalActions:0,globalKillSwitchRequired:true,productionGate:'blocked',nextRequiredGate:'arm_single_mission_execution_separately',provenance:{source:'control-broker',sourceId:`a1-assignment-execution-authorization:${EXECUTION_ID}`,observedAt:NOW.toISOString(),synthetic:false}}as const}

describe('A1 exact assignment execution authorization',()=>{
 it('validates one short-lived record-only prerequisite',()=>{const value=validateA1AssignmentExecutionAuthorizationRequest(request(),NOW);assert.equal(value.expectedJobSetSha256,hashA1JobSet(plan()));assert.equal(value.maximumProviderCreditSpendUsd,0.01);assert.equal(value.attestations.executionArmRequiresSeparateGate,true)})
 it('rejects recovery identity, false safeguards, changed budget and stale time',()=>{assert.throws(()=>validateA1AssignmentExecutionAuthorizationRequest({...request(),reviewer_email:'lamrobcompany@gmail.com'},NOW),/A1_ASSIGNMENT_EXECUTION_AUTHORIZATION_INVALID/);assert.throws(()=>validateA1AssignmentExecutionAuthorizationRequest({...request(),attestations:{...attestations(),no_execution:false}},NOW),/A1_ASSIGNMENT_EXECUTION_AUTHORIZATION_INVALID/);assert.throws(()=>validateA1AssignmentExecutionAuthorizationRequest({...request(),maximum_provider_credit_spend_usd:0.02},NOW),/A1_ASSIGNMENT_EXECUTION_AUTHORIZATION_INVALID/);assert.throws(()=>validateA1AssignmentExecutionAuthorizationRequest({...request(),reviewed_at:'2026-08-29T19:54:59.000Z'},NOW),/A1_ASSIGNMENT_EXECUTION_AUTHORIZATION_INVALID/)})
 it('binds exact job set while keeping claiming and spend disabled',()=>{const value=validateA1AssignmentExecutionAuthorizationState(state());assert.equal(value.dispatchClaimingPermitted,false);assert.equal(value.providerCreditSpendAllowed,false);assert.doesNotThrow(()=>assertA1AssignmentExecutionAuthorizationAdmission(mission(),plan(),parent(),state(),NOW));const changed=plan();changed.assignments[0].assignment_id='a5500000-0000-4500-8500-000000000059';assert.throws(()=>assertA1AssignmentExecutionAuthorizationAdmission(mission(),changed,parent(),state(),NOW),/A1_ASSIGNMENT_EXECUTION_AUTHORIZATION_GATE_CLOSED/)})
 it('ships a database claim interlock with an empty arm table',async()=>{const sql=await readFile(new URL('../migrations/032_a1_assignment_execution_authorization.sql',import.meta.url),'utf8');assert.match(sql,/CREATE TABLE control\.a1_dispatch_execution_arms/);assert.match(sql,/JOIN control\.a1_dispatch_execution_arms/);assert.match(sql,/NOT control\.is_global_kill_switch_active\(\)/);assert.match(sql,/control\.external_actions_blocked\(\)/);assert.match(sql,/'dispatchClaimingPermitted',false/);assert.doesNotMatch(sql,/INSERT INTO control\.a1_dispatch_execution_arms|mail\.send|integration\.enqueue_crm_change/i);const rollback=await readFile(new URL('../migrations/032_a1_assignment_execution_authorization.rollback.sql',import.meta.url),'utf8');assert.match(rollback,/A1_ASSIGNMENT_EXECUTION_AUTHORIZATION_HISTORY_PRESENT/)})
 it('exposes only a record-only authorization route before a separate arm gate',async()=>{const source=await readFile(new URL('../src/application.ts',import.meta.url),'utf8');assert.match(source,/a1-assignment-execution-authorizations/);assert.match(source,/recordA1AssignmentExecutionAuthorization/);assert.match(source,/execution\.assignments\.some\(item=>item\.status!==\'queued\'\|\|item\.attempts!==0\)/)})
})
