import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { describe,it } from 'node:test'
import { hashA1AssignmentPlan,hashA1Mission } from '../src/a1-dispatch-authorization.js'
import { hashA1JobSet,sumA1PlanReservations,type A1AssignmentExecutionAuthorizationState } from '../src/a1-assignment-execution-authorization.js'
import { assertA1DispatchExecutionArmAdmission,hashA1DispatchExecutionArm,validateA1DispatchExecutionArmRequest,validateA1DispatchExecutionArmState } from '../src/a1-dispatch-execution-arm.js'
import type { AssignmentPlan } from '../src/assignment-plan.js'
import type { MissionRecord } from '../src/repository.js'

const NOW=new Date('2026-08-29T20:00:00.000Z'),MISSION_ID='a6500000-0000-4500-8500-000000000053',TRACE_ID='a6500000-0000-4500-8500-000000000054',EXECUTION_ID='a6500000-0000-4500-8500-000000000055',ARM_ID='a6500000-0000-4500-8500-000000000056',AUTH_ID='a6500000-0000-4500-8500-000000000057'
function mission():MissionRecord{return{mission_id:MISSION_ID,trace_id:TRACE_ID,autonomy_level:'A1',a3_enabled:false,dry_run:true,project_id:'proptimiza',offer_id:'operacion-sin-planillas'}}
function plan():AssignmentPlan{return{mission_id:MISSION_ID,trace_id:TRACE_ID,plan_version:'a1-plan-v1',assignments:[{assignment_id:'a6500000-0000-4500-8500-000000000058',idempotency_key:'a1-assignment:00000053',profile_id:'sales-orchestrator',instruction:'Clasificar únicamente evidencia interna aprobada.',evidence:'Expediente interno.',depends_on:[],usage_value_reservation_usd:0.01,maximum_tokens:6144,maximum_api_calls:3,max_attempts:1}]}}
function attestations(){return{exact_job_set_confirmed:true,single_use_arm_confirmed:true,arm_creation_only:true,no_jobs_claimed_by_arm_creation:true,no_execution:true,no_internet:true,no_contact:true,no_crm_write:true,no_external_actions:true,no_provider_credit_spend:true,global_kill_switch_must_remain_active:true,dispatcher_window_requires_separate_gate:true,external_channels_blocked:true,timer_disabled_confirmed:true}as const}
function request(){return{decision:'approved',rationale:'Crea solamente un arm exacto; no abre la ventana ni ejecuta trabajos.',reviewer_id:'director',reviewer_email:'proptimizaspa@gmail.com',reviewed_at:NOW.toISOString(),starts_at:'2026-08-29T20:01:00.000Z',expires_at:'2026-08-29T20:15:00.000Z',expected_mission_sha256:hashA1Mission(mission()),expected_assignment_plan_sha256:hashA1AssignmentPlan(plan()),expected_job_set_sha256:hashA1JobSet(plan()),expected_execution_authorization_id:EXECUTION_ID,worker_id:'broker-dispatcher-1',maximum_claims:1,maximum_provider_credit_spend_usd:sumA1PlanReservations(plan()),user_authorization_sha256:'f'.repeat(64),attestations:attestations(),idempotency_key:'a1-execution-arm:mission-00000053',assignment_plan:plan()}}
function parent():A1AssignmentExecutionAuthorizationState{return{authorizationId:EXECUTION_ID,missionId:MISSION_ID,traceId:TRACE_ID,planVersion:'a1-plan-v1',enqueueAuthorizationId:'a6500000-0000-4500-8500-000000000059',decision:'approved',rationale:'Registra solamente el prerrequisito exacto; no inicia ni ejecuta jobs.',reviewerId:'director',reviewerEmail:'proptimizaspa@gmail.com',reviewedAt:NOW.toISOString(),expiresAt:'2026-08-29T20:20:00.000Z',missionSha256:hashA1Mission(mission()),assignmentPlanSha256:hashA1AssignmentPlan(plan()),jobSetSha256:hashA1JobSet(plan()),assignmentIds:plan().assignments.map(item=>item.assignment_id),maximumProviderCreditSpendUsd:0.01,userAuthorizationSha256:'e'.repeat(64),attestations:{exactJobSetConfirmed:true,authorizationRecordOnly:true,noJobsClaimedByAuthorization:true,noExecution:true,noInternet:true,noContact:true,noCrmWrite:true,noExternalActions:true,noProviderCreditSpend:true,globalKillSwitchRequired:true,executionArmRequiresSeparateGate:true},idempotencyKey:'a1-execution-auth:mission-00000053',executionAuthorizationRecorded:true,dispatchExecutionEligible:true,executionArmCreated:false,dispatchClaimingPermitted:false,jobsClaimed:false,executionStarted:false,internetAccessAllowed:false,providerCreditSpendAllowed:false,contactPermitted:false,crmWriteAllowed:false,maximumExternalActions:0,globalKillSwitchRequired:true,productionGate:'blocked',nextRequiredGate:'arm_single_mission_execution_separately',provenance:{source:'control-broker',sourceId:`a1-assignment-execution-authorization:${EXECUTION_ID}`,observedAt:NOW.toISOString(),synthetic:false}}}
function state(){return{armId:ARM_ID,authorizationId:AUTH_ID,missionId:MISSION_ID,traceId:TRACE_ID,planVersion:'a1-plan-v1',executionAuthorizationId:EXECUTION_ID,decision:'approved',rationale:'Crea solamente un arm exacto; no abre la ventana ni ejecuta trabajos.',reviewerId:'director',reviewerEmail:'proptimizaspa@gmail.com',reviewedAt:NOW.toISOString(),startsAt:'2026-08-29T20:01:00.000Z',expiresAt:'2026-08-29T20:15:00.000Z',missionSha256:hashA1Mission(mission()),assignmentPlanSha256:hashA1AssignmentPlan(plan()),jobSetSha256:hashA1JobSet(plan()),assignmentIds:plan().assignments.map(item=>item.assignment_id),workerId:'broker-dispatcher-1',maximumClaims:1,maximumProviderCreditSpendUsd:0.01,userAuthorizationSha256:'f'.repeat(64),attestations:{exactJobSetConfirmed:true,singleUseArmConfirmed:true,armCreationOnly:true,noJobsClaimedByArmCreation:true,noExecution:true,noInternet:true,noContact:true,noCrmWrite:true,noExternalActions:true,noProviderCreditSpend:true,globalKillSwitchMustRemainActive:true,dispatcherWindowRequiresSeparateGate:true,externalChannelsBlocked:true,timerDisabledConfirmed:true},idempotencyKey:'a1-execution-arm:mission-00000053',armAuthorizationRecorded:true,executionArmCreated:true,claimsUsed:0,executionWindowEnabled:false,dispatchClaimingPermitted:false,jobsClaimed:false,executionStarted:false,internetAccessAllowed:false,providerCreditSpendAllowed:false,contactPermitted:false,crmWriteAllowed:false,maximumExternalActions:0,globalKillSwitchActive:true,externalChannelsBlocked:true,dispatcherTimerDisabled:true,productionGate:'blocked',nextRequiredGate:'open_single_mission_execution_window_separately',provenance:{source:'control-broker',sourceId:`a1-dispatch-execution-arm:${ARM_ID}`,observedAt:NOW.toISOString(),synthetic:false}}as const}

describe('A1 exact dispatch execution arm',()=>{
 it('validates one exact short-lived arm without opening an execution window',()=>{const value=validateA1DispatchExecutionArmRequest(request(),NOW);assert.equal(value.maximumClaims,1);assert.equal(value.workerId,'broker-dispatcher-1');assert.equal(value.attestations.dispatcherWindowRequiresSeparateGate,true);assert.match(hashA1DispatchExecutionArm({missionId:MISSION_ID,executionAuthorizationId:EXECUTION_ID,jobSetSha256:value.expectedJobSetSha256,workerId:value.workerId,startsAt:value.startsAt,expiresAt:value.expiresAt,maximumClaims:value.maximumClaims,maximumProviderCreditSpendUsd:value.maximumProviderCreditSpendUsd}),/^[0-9a-f]{64}$/)})
 it('rejects recovery identity, altered claim count, unsafe attestation and stale review',()=>{assert.throws(()=>validateA1DispatchExecutionArmRequest({...request(),reviewer_email:'lamrobcompany@gmail.com'},NOW),/A1_DISPATCH_EXECUTION_ARM_INVALID/);assert.throws(()=>validateA1DispatchExecutionArmRequest({...request(),maximum_claims:2},NOW),/A1_DISPATCH_EXECUTION_ARM_INVALID/);assert.throws(()=>validateA1DispatchExecutionArmRequest({...request(),attestations:{...attestations(),no_execution:false}},NOW),/A1_DISPATCH_EXECUTION_ARM_INVALID/);assert.throws(()=>validateA1DispatchExecutionArmRequest({...request(),reviewed_at:'2026-08-29T19:54:59.000Z'},NOW),/A1_DISPATCH_EXECUTION_ARM_INVALID/)})
 it('binds the exact parent authorization, job set and budget',()=>{const input=validateA1DispatchExecutionArmRequest(request(),NOW);assert.doesNotThrow(()=>assertA1DispatchExecutionArmAdmission(mission(),plan(),parent(),input,NOW));assert.throws(()=>assertA1DispatchExecutionArmAdmission(mission(),plan(),parent(),{...input,expectedJobSetSha256:'0'.repeat(64)},NOW),/A1_DISPATCH_EXECUTION_ARM_GATE_CLOSED/)})
 it('validates an inert arm state with claiming still blocked',()=>{const value=validateA1DispatchExecutionArmState(state());assert.equal(value.executionArmCreated,true);assert.equal(value.executionWindowEnabled,false);assert.equal(value.dispatchClaimingPermitted,false);assert.equal(value.providerCreditSpendAllowed,false)})
 it('ships a third database interlock and no execution-window opener',async()=>{const sql=await readFile(new URL('../migrations/033_a1_dispatch_execution_arm.sql',import.meta.url),'utf8');assert.match(sql,/CREATE TABLE control\.a1_dispatch_execution_control/);assert.match(sql,/ctl\.claiming_enabled/);assert.match(sql,/INSERT INTO control\.a1_dispatch_execution_arms/);assert.match(sql,/'executionWindowEnabled',false/);assert.doesNotMatch(sql,/UPDATE control\.a1_dispatch_execution_control SET claiming_enabled=true|set_kill_switch\([^)]*false|mail\.send|integration\.enqueue_crm_change/i);const rollback=await readFile(new URL('../migrations/033_a1_dispatch_execution_arm.rollback.sql',import.meta.url),'utf8');assert.match(rollback,/A1_DISPATCH_EXECUTION_ARM_HISTORY_PRESENT/)})
 it('exposes only the record-arm route before a separate execution-window gate',async()=>{const source=await readFile(new URL('../src/application.ts',import.meta.url),'utf8');assert.match(source,/a1-dispatch-execution-arms/);assert.match(source,/recordA1DispatchExecutionArm/);assert.doesNotMatch(source,/openA1DispatchExecutionWindow|enableA1DispatchExecutionWindow/)})
})
