export function validWorkOrder() {
  return {
    mission_id: '123e4567-e89b-42d3-a456-426614174000',
    trace_id: '223e4567-e89b-42d3-a456-426614174000',
    created_at: '2026-08-15T19:00:00.000Z',
    expires_at: '2026-08-15T21:00:00.000Z',
    project_id: 'proptimiza',
    project_version: 'v1',
    offer_id: 'operacion-sin-planillas',
    offer_version: 'v1',
    icp_version: 'v1',
    policy_version: 'v1',
    objective: 'Validar el circuito interno',
    business_context: 'Prueba controlada sin prospectos externos',
    target_segment: 'Buzón interno Proptimiza',
    allowed_actions: ['mail.send'],
    prohibited_actions: ['prospect.contact'],
    approved_channels: ['email'],
    approved_tools: ['broker.mail'],
    autonomy_level: 'A3',
    budget_limit: { currency: 'CLP', maximum: 0 },
    volume_limits: {
      maximum_accounts: 1,
      maximum_contacts: 1,
      maximum_external_actions: 1,
      maximum_per_contact: 1,
      period: 'mission',
    },
    success_criteria: ['Un correo interno con recibo'],
    stop_conditions: ['Cualquier discrepancia'],
    required_evidence: ['Recibo del conector'],
    approval_token: null,
    idempotency_key: 'mission-internal-0001',
    requested_by: 'codex-control-plane',
    authority: {
      issuer: 'codex',
      audience: 'hermes-commercial-orchestrator',
      key_id: 'control-key-1',
      algorithm: 'HMAC-SHA256',
      signature: 'a'.repeat(64),
    },
    data_policy: {
      classification: 'internal',
      allowed_countries: ['CL'],
      legal_basis: ['none'],
      retention_days: 30,
      sensitive_data_allowed: false,
    },
    contact_policy: {
      contact_permitted: true,
      suppression_check_required: true,
      consent_check_required: false,
      maximum_frequency_days: 30,
      quiet_hours_timezone: 'America/Santiago',
    },
    dry_run: false,
    metadata: { a3_enabled: true },
  }
}
