BEGIN;
CREATE TABLE IF NOT EXISTS control.dispatch_jobs(
 job_id uuid PRIMARY KEY,mission_id uuid NOT NULL REFERENCES control.missions(mission_id) ON DELETE RESTRICT,idempotency_key text NOT NULL,profile_id text NOT NULL CHECK(profile_id IN('sales-orchestrator','market-account-intelligence','contact-data-steward','qualification-prioritization','outreach-draft-manager','commercial-qa-compliance')),prompt jsonb NOT NULL CHECK(prompt->>'trust'='untrusted_data' AND jsonb_typeof(prompt->'text')='string'),status text NOT NULL CHECK(status IN('queued','leased','succeeded','failed','budget_exceeded')),attempts integer NOT NULL DEFAULT 0,max_attempts integer NOT NULL CHECK(max_attempts BETWEEN 1 AND 10),maximum_cost numeric(14,6) NOT NULL CHECK(maximum_cost>=0),maximum_tokens bigint NOT NULL CHECK(maximum_tokens>=0),lease_owner text,lease_until timestamptz,next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp(),result_envelope jsonb,artifact_sha256 text CHECK(artifact_sha256~'^[0-9a-f]{64}$'),cost_amount numeric(14,6),tokens_used bigint,error text,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(mission_id,idempotency_key),CHECK((status='leased')=(lease_owner IS NOT NULL AND lease_until IS NOT NULL)));
CREATE INDEX IF NOT EXISTS dispatch_jobs_claim_idx ON control.dispatch_jobs(status,next_attempt_at,created_at);
CREATE INDEX IF NOT EXISTS dispatch_jobs_mission_idx ON control.dispatch_jobs(mission_id);
CREATE TABLE IF NOT EXISTS control.dispatch_dependencies(job_id uuid NOT NULL REFERENCES control.dispatch_jobs(job_id) ON DELETE CASCADE,depends_on_job_id uuid NOT NULL REFERENCES control.dispatch_jobs(job_id) ON DELETE RESTRICT,PRIMARY KEY(job_id,depends_on_job_id),CHECK(job_id<>depends_on_job_id));
CREATE INDEX IF NOT EXISTS dispatch_dependencies_depends_idx ON control.dispatch_dependencies(depends_on_job_id);
CREATE TABLE IF NOT EXISTS control.dispatch_events(event_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,job_id uuid NOT NULL REFERENCES control.dispatch_jobs(job_id) ON DELETE RESTRICT,from_status text,to_status text NOT NULL,reason text,occurred_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE INDEX IF NOT EXISTS dispatch_events_job_idx ON control.dispatch_events(job_id,event_id);
DO $$BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='dispatch_events_append_only' AND tgrelid='control.dispatch_events'::regclass)THEN CREATE TRIGGER dispatch_events_append_only BEFORE UPDATE OR DELETE ON control.dispatch_events FOR EACH STATEMENT EXECUTE FUNCTION control.reject_audit_event_mutation();END IF;END$$;

CREATE OR REPLACE FUNCTION control.enqueue_dispatch(uuid,uuid,text,text,text,uuid[],numeric,bigint,integer) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE existing control.dispatch_jobs%ROWTYPE;d uuid;stored_dependencies uuid[];requested_dependencies uuid[];BEGIN IF $4 NOT IN('sales-orchestrator','market-account-intelligence','contact-data-steward','qualification-prioritization','outreach-draft-manager','commercial-qa-compliance')THEN RAISE EXCEPTION'UNKNOWN_PROFILE';END IF;INSERT INTO control.dispatch_jobs(job_id,mission_id,idempotency_key,profile_id,prompt,status,maximum_cost,maximum_tokens,max_attempts)VALUES($1,$2,$3,$4,jsonb_build_object('trust','untrusted_data','text',$5),'queued',$7,$8,$9)ON CONFLICT DO NOTHING;IF FOUND THEN FOREACH d IN ARRAY $6 LOOP INSERT INTO control.dispatch_dependencies VALUES($1,d);END LOOP;INSERT INTO control.dispatch_events(job_id,from_status,to_status,reason)VALUES($1,NULL,'queued','enqueued');RETURN $1;END IF;SELECT*INTO existing FROM control.dispatch_jobs WHERE mission_id=$2 AND idempotency_key=$3;SELECT coalesce(array_agg(depends_on_job_id ORDER BY depends_on_job_id),ARRAY[]::uuid[])INTO stored_dependencies FROM control.dispatch_dependencies WHERE job_id=existing.job_id;SELECT coalesce(array_agg(value ORDER BY value),ARRAY[]::uuid[])INTO requested_dependencies FROM unnest($6)value;IF existing.job_id=$1 AND existing.profile_id=$4 AND existing.prompt=jsonb_build_object('trust','untrusted_data','text',$5)AND existing.maximum_cost=$7 AND existing.maximum_tokens=$8 AND existing.max_attempts=$9 AND stored_dependencies=requested_dependencies THEN RETURN existing.job_id;END IF;RAISE EXCEPTION'DISPATCH_IDEMPOTENCY_CONFLICT';END$$;
CREATE OR REPLACE FUNCTION control.recover_dispatch_leases(timestamptz) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE n integer;BEGIN WITH changed AS(UPDATE control.dispatch_jobs SET status=CASE WHEN attempts<max_attempts THEN'queued'ELSE'failed'END,lease_owner=NULL,lease_until=NULL,next_attempt_at=$1,updated_at=$1,error='LEASE_EXPIRED' WHERE status='leased'AND lease_until<=$1 RETURNING job_id,status)INSERT INTO control.dispatch_events(job_id,from_status,to_status,reason)SELECT job_id,'leased',status,'LEASE_EXPIRED'FROM changed;GET DIAGNOSTICS n=ROW_COUNT;RETURN n;END$$;
CREATE OR REPLACE FUNCTION control.claim_dispatch(text,timestamptz,integer) RETURNS SETOF control.dispatch_jobs LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE selected uuid;BEGIN IF $1 IS NULL OR btrim($1)=''OR $2 IS NULL OR $3 NOT BETWEEN 1 AND 3600 THEN RAISE EXCEPTION'INVALID_DISPATCH_LEASE';END IF;PERFORM control.recover_dispatch_leases($2);SELECT j.job_id INTO selected FROM control.dispatch_jobs j WHERE j.status='queued'AND j.next_attempt_at<=$2 AND j.attempts<j.max_attempts AND NOT control.is_kill_switch_active(j.mission_id::text,'internal')AND NOT EXISTS(SELECT 1 FROM control.dispatch_dependencies d JOIN control.dispatch_jobs p ON p.job_id=d.depends_on_job_id WHERE d.job_id=j.job_id AND p.status<>'succeeded')ORDER BY j.created_at,j.job_id FOR UPDATE SKIP LOCKED LIMIT 1;IF selected IS NULL THEN RETURN;END IF;UPDATE control.dispatch_jobs SET status='leased',lease_owner=$1,lease_until=$2+make_interval(secs=>$3),attempts=attempts+1,updated_at=$2 WHERE job_id=selected;INSERT INTO control.dispatch_events VALUES(DEFAULT,selected,'queued','leased','claimed',$2);RETURN QUERY SELECT*FROM control.dispatch_jobs WHERE job_id=selected;END$$;
CREATE OR REPLACE FUNCTION control.fail_dispatch(uuid,text,text,boolean,timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE target text;BEGIN SELECT CASE WHEN $4 AND attempts<max_attempts THEN'queued'ELSE'failed'END INTO target FROM control.dispatch_jobs WHERE job_id=$1 AND status='leased'AND lease_owner=$2 FOR UPDATE;IF target IS NULL THEN RAISE EXCEPTION'DISPATCH_LEASE_CONFLICT';END IF;UPDATE control.dispatch_jobs SET status=target,lease_owner=NULL,lease_until=NULL,next_attempt_at=$5,error=$3,updated_at=$5 WHERE job_id=$1;INSERT INTO control.dispatch_events VALUES(DEFAULT,$1,'leased',target,$3,$5);END$$;
CREATE OR REPLACE FUNCTION control.complete_dispatch(uuid,text,jsonb,text,numeric,bigint,bigint,timestamptz) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE target text;BEGIN IF $5 IS NULL OR $5='NaN'::numeric OR $5<0 OR $6 IS NULL OR $6<0 OR $7 IS NULL OR $7<0 THEN RAISE EXCEPTION'INVALID_DISPATCH_COST';END IF;SELECT CASE WHEN $5<=maximum_cost AND($6+$7)<=maximum_tokens THEN'succeeded'ELSE'budget_exceeded'END INTO target FROM control.dispatch_jobs WHERE job_id=$1 AND status='leased'AND lease_owner=$2 AND lease_until>$8 FOR UPDATE;IF target IS NULL THEN RAISE EXCEPTION'DISPATCH_LEASE_CONFLICT';END IF;UPDATE control.dispatch_jobs SET status=target,lease_owner=NULL,lease_until=NULL,result_envelope=$3,artifact_sha256=$4,cost_amount=$5,tokens_used=$6+$7,updated_at=$8 WHERE job_id=$1;INSERT INTO control.dispatch_events VALUES(DEFAULT,$1,'leased',target,CASE WHEN target='budget_exceeded'THEN'BUDGET_EXCEEDED'ELSE'completed'END,$8);RETURN target;END$$;
REVOKE ALL ON control.dispatch_jobs,control.dispatch_dependencies,control.dispatch_events FROM PUBLIC,commercial_runtime,commercial_approver,commercial_safety_operator,commercial_observer;
REVOKE ALL ON SEQUENCE control.dispatch_events_event_id_seq FROM PUBLIC,commercial_runtime,commercial_approver,commercial_safety_operator,commercial_observer;
REVOKE ALL ON FUNCTION control.enqueue_dispatch(uuid,uuid,text,text,text,uuid[],numeric,bigint,integer),control.recover_dispatch_leases(timestamptz),control.claim_dispatch(text,timestamptz,integer),control.fail_dispatch(uuid,text,text,boolean,timestamptz),control.complete_dispatch(uuid,text,jsonb,text,numeric,bigint,bigint,timestamptz) FROM PUBLIC,commercial_runtime,commercial_approver,commercial_safety_operator,commercial_observer;
GRANT EXECUTE ON FUNCTION control.enqueue_dispatch(uuid,uuid,text,text,text,uuid[],numeric,bigint,integer),control.recover_dispatch_leases(timestamptz),control.claim_dispatch(text,timestamptz,integer),control.fail_dispatch(uuid,text,text,boolean,timestamptz),control.complete_dispatch(uuid,text,jsonb,text,numeric,bigint,bigint,timestamptz) TO commercial_runtime;
COMMIT;
